trebol-ecommerce/trebol-backend-monolith

pom.xml, src/main/java/org/trebol/api/pojo/PersonPojo.java, src/main/java/org/trebol/jpa/entities/Person.java
update class type for person phones
add regex to personpojo phones
remove validations from non-required properties
=> Update Person metadata according to API v2.7.0

src/main/java/org/trebol/jpa/services/GenericCrudJpaService.java, src/main/java/org/trebol/jpa/services/ICrudJpaService.java, src/main/java/org/trebol/jpa/services/predicates/PeoplePredicateJpaServiceImpl.java, src/main/java/org/trebol/operation/GenericDataController.java, src/main/java/org/trebol/operation/controllers/AccessController.java, src/main/java/org/trebol/operation/controllers/PublicCategoriesController.java, src/main/java/org/trebol/operation/controllers/PublicProductsController.java, src/main/resources/application.properties, src/test/java/org/trebol/jpa/services/GenericJpaCrudServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/BillingCompaniesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/BillingTypesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/CustomersPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/ImagesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/PeoplePredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/ProductCategoriesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/ProductsPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/SalesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/SalespeoplePredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/SellStatusesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/ShippersPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/UserRolesPredicateJpaServiceTest.java, src/test/java/org/trebol/jpa/services/predicate/UsersPredicateJpaServiceTest.java, src/test/java/org/trebol/operation/controllers/PublicProductsControllerTest.java, src/test/java/org/trebol/operation/services/CheckoutServiceTest.java
=> Unit tests for jpa predicate services

CHANGELOG.md, src/main/java/org/trebol/operation/controllers/DataCustomersController.java, src/main/java/org/trebol/operation/controllers/DataImagesController.java, src/main/java/org/trebol/operation/controllers/DataProductCategoriesController.java, src/main/java/org/trebol/operation/controllers/DataProductsController.java, src/main/java/org/trebol/operation/controllers/DataSalesController.java, src/main/java/org/trebol/operation/controllers/DataSalespeopleController.java, src/main/java/org/trebol/operation/controllers/DataUserRolesController.java, src/main/java/org/trebol/operation/controllers/DataUsersController.java, src/main/java/org/trebol/operation/controllers/PublicCategoriesController.java, src/main/java/org/trebol/operation/controllers/PublicProductsController.java
This PR must:
- resolve #94
- resolve #95
- resolve #96
=> Update existing APIs to comply with specification v1.2.1

CHANGELOG.md, src/main/java/org/trebol/config/OperationProperties.java, src/main/java/org/trebol/operation/GenericPaginationController.java, src/main/resources/application.properties
add property to `properties` file
use it in the base method where page size is figured out
silently change to max if too high
resolves #97
=> Add page size limit

pom.xml, src/main/java/org/trebol/jpa/services/conversion/UsersConverterJpaServiceImpl.java, src/test/java/org/trebol/constant/TestContants.java, src/test/java/org/trebol/jpa/services/conversion/BillingCompaniesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/CustomersConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ImagesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/PeopleConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ProductCategoriesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ProductListConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ProductListItemsConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ProductsConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/SalesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/SalespeopleConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/SellStatusesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/ShippersConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/UserRolesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/UsersConverterJpaServiceImplTest.java
Write unit tests for org.trebol.jpa.services.conversion
=> Resolve issue #86

CHANGELOG.md, src/main/java/org/trebol/jpa/entities/ProductCategory.java, src/main/java/org/trebol/jpa/entities/ProductImage.java, src/main/java/org/trebol/jpa/entities/SellStatus.java, src/main/java/org/trebol/jpa/entities/UserRole.java, src/main/java/org/trebol/jpa/entities/UserRolePermission.java, src/main/resources/data.sql, src/main/resources/schema-mariadb.sql
I added the changes to the changelog as well.
=> Close issue #100

README.md
- Spring Boot v2.6 documentation
- Spring Data JPA project overview
- Spring Security project overview
- JWT and the implementing library
=> docs: add several useful links [skip ci]

src/test/java/org/trebol/jpa/services/conversion/SalesConverterJpaServiceImplTest.java, src/test/java/org/trebol/operation/controllers/AccessControllerTest.java, src/test/java/org/trebol/operation/controllers/AccountProfileControllerTest.java, src/test/java/org/trebol/operation/controllers/DataBillingTypesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataCustomersControllerTest.java, src/test/java/org/trebol/operation/controllers/DataImagesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataPeopleControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductCategoriesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductListContentsControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductListsControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSalesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSalespeopleControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSellStatusesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataShippersControllerTest.java, src/test/java/org/trebol/operation/controllers/DataUserRolesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataUsersControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicAboutControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicCheckoutControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicReceiptControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicRegisterControllerTest.java, src/test/java/org/trebol/operation/services/CheckoutServiceTest.java
Some of the classes are not applicable to reduce because they are abstract classes
=> Apply injectmocks usage/reduce system under test instantiation

src/test/java/org/trebol/jpa/services/conversion/ProductCategoriesConverterJpaServiceImplTest.java, src/test/java/org/trebol/jpa/services/conversion/SalesConverterJpaServiceImplTest.java, src/test/java/org/trebol/operation/controllers/AccessControllerTest.java, src/test/java/org/trebol/operation/controllers/AccountProfileControllerTest.java, src/test/java/org/trebol/operation/controllers/DataBillingTypesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataCustomersControllerTest.java, src/test/java/org/trebol/operation/controllers/DataImagesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataPeopleControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductCategoriesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductListContentsControllerTest.java, src/test/java/org/trebol/operation/controllers/DataProductListsControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSalesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSalespeopleControllerTest.java, src/test/java/org/trebol/operation/controllers/DataSellStatusesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataShippersControllerTest.java, src/test/java/org/trebol/operation/controllers/DataUserRolesControllerTest.java, src/test/java/org/trebol/operation/controllers/DataUsersControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicAboutControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicCheckoutControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicReceiptControllerTest.java, src/test/java/org/trebol/operation/controllers/PublicRegisterControllerTest.java, src/test/java/org/trebol/operation/services/CheckoutServiceTest.java
Issue  #132 
- Removed commented code
- Removed @BeforeEach annotated methods which enclosed the commented code
- Removed unused imports
=> Clean up test code resulting from

.editorconfig, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, pom.xml
- Bump project version one patch up (`3.0.1.SNAPSHOT` to `3.0.2-SNAPSHOT`, also fixed semver syntax there)
- Issue and Pull Request templates
- [.editorconfig](https://editorconfig.org) file
- Update to latest Spring Boot patch (as of Oct 12th, 2022)
- `spring-boot-starter-parent` - `2.6.4` to `2.6.12`
=> housekeeping for v3.0.2

CHANGELOG.md, src/test/java/org/trebol/annotation/PhoneNumberValidatorTest.java
Resolve code smell tag by sonar cloud and use @ParameterizedTest
=> Refactor PhoneNumberValidatorTest

CHANGELOG.md, src/test/java/org/trebol/operation/services/RegistrationServiceImplTest.java
Unit tests for `RegistrationServiceImpl`
None.
=> Close #147 - added unit tests for `RegistrationServiceImpl`

CHANGELOG.md, src/test/java/org/trebol/operation/services/ProfileServiceImplTest.java
Add unit tests for `ProfileServiceImpl`
=> Close #145 - add unit tests for `ProfileServiceImpl`

CHANGELOG.md, src/test/java/org/trebol/operation/services/SalesProcessServiceImplTest.java
Add unit test for SalesProcessServiceImpl, issue #148 
- Used @Nested classes to separate the methods
- Mock objects were setup at the beginning of each test methods so it's easier to see what are they (no need to scroll up and down)
Thanks @NyorJa for the help how to mock multiple interfaces which uses generics #167
=> Close #148 - add unit test for SalesProcessServiceImpl

CHANGELOG.md, src/test/java/org/trebol/operation/services/ReceiptServiceImplTest.java
Add unit test for `ReceiptServiceImpl`
=> Close #146 - add unit test for `ReceiptServiceImpl`

CHANGELOG.md, src/test/java/org/trebol/jpa/services/crud/ProductListJpaCrudServiceImplTest.java
Add unit test for ProductListJpaCrudServiceImp
=> Close 171 -  Add unit test for ProductListJpaCrudServiceImp

src/main/java/org/trebol/config/Constants.java
Fix sonar issue by adding private constructor in Constants class and making the class as final.
=> Add private constructor in Constants class and make class final

pom.xml, src/main/java/org/trebol/jpa/services/conversion/PeopleConverterJpaServiceImpl.java
Improved the if statement to make the code shorter and easy to understand
=> improved the if statement

CONTRIBUTING.md
Improve contribution guidelines to match the existing state and recommended ways to do things here on this project. These were **too outdated**!
=> docs: update contribution guidelines [skip ci]

src/main/java/org/trebol/jpa/services/GenericCrudJpaService.java
=> fix: change class to protected

src/main/java/org/trebol/integration/payments/webpayplus/WebpayplusPaymentServiceImpl.java
=> fix: sonar issue primitive boolean

src/main/java/org/trebol/jpa/services/conversion/ProductsConverterJpaServiceImpl.java
=> fix: remove unnecesary condition

README.md
Fix broken link to the current Trebol API.
=> docs: fix a readme link [skip ci]

src/main/java/org/trebol/jpa/services/conversion/CustomersConverterJpaServiceImpl.java, src/test/java/org/trebol/jpa/services/conversion/CustomersConverterJpaServiceImplTest.java
=> fix: sonar issue always false

src/main/java/org/trebol/integration/mailing/mailgun/MailgunMailingServiceImpl.java
=> fix: sonar issue reorder

src/main/java/org/trebol/jpa/services/conversion/BillingTypesConverterJpaServiceImpl.java
Removed the condition name !=null that was redundant.
=> removed the expression always evaluating to true

src/main/java/org/trebol/operation/controllers/DataBillingTypesController.java, src/main/java/org/trebol/operation/controllers/DataCustomersController.java, src/main/java/org/trebol/operation/controllers/DataImagesController.java, src/main/java/org/trebol/operation/controllers/DataPeopleController.java, src/main/java/org/trebol/operation/controllers/DataProductCategoriesController.java, src/main/java/org/trebol/operation/controllers/DataProductListsController.java, src/main/java/org/trebol/operation/controllers/DataProductsController.java, src/main/java/org/trebol/operation/controllers/DataSalesController.java, src/main/java/org/trebol/operation/controllers/DataSalespeopleController.java, src/main/java/org/trebol/operation/controllers/DataSellStatusesController.java, src/main/java/org/trebol/operation/controllers/DataShippersController.java, src/main/java/org/trebol/operation/controllers/DataUserRolesController.java, src/main/java/org/trebol/operation/controllers/DataUsersController.java
Fixes #169 
Override annotations used above methods in Data Controllers.
=> Add missing Override annotations in Data Controllers

.github/workflows/build.yml, CHANGELOG.md
Updates GitHub Actions workflow versions. Closes #172
Thanks for reporting this, @mepox!
=> build(github): update actions workflows

src/main/java/org/trebol/api/controllers/AccessController.java, src/main/java/org/trebol/api/controllers/PublicCheckoutController.java, src/main/java/org/trebol/common/services/RegexMatcherAdapterService.java, src/main/java/org/trebol/common/services/impl/RegexMatcherAdapterServiceImpl.java, src/main/java/org/trebol/config/Constants.java, src/main/java/org/trebol/config/SecurityConfig.java, src/main/java/org/trebol/jpa/repositories/UserRolePermissionsRepository.java, src/main/java/org/trebol/jpa/services/patch/impl/SalesPatchServiceImpl.java, src/main/java/org/trebol/security/GenericJwtAuthenticationFilter.java, src/main/java/org/trebol/security/JwtGuestAuthenticationFilter.java, src/main/java/org/trebol/security/JwtTokenVerifierFilter.java, src/main/java/org/trebol/security/UserDetailsPojo.java, src/main/java/org/trebol/security/UserDetailsServiceImpl.java, src/test/java/org/trebol/api/controllers/AccessControllerTest.java, src/test/java/org/trebol/jpa/services/patch/impl/SalesPatchServiceImplTest.java, src/test/java/org/trebol/security/JwtGuestAuthenticationFilterTest.java, src/test/java/org/trebol/security/JwtLoginAuthenticationFilterTest.java, src/test/java/org/trebol/security/JwtVerifiterFilterTest.java, src/test/java/org/trebol/security/SecurityTestingConfig.java, src/test/java/org/trebol/security/UserDetailsServiceImplTest.java, src/test/java/org/trebol/security/services/impl/AuthorizedApiServiceImplTest.java, src/test/java/org/trebol/security/services/impl/ClaimsAuthorizationHeaderParserServiceImplTest.java, src/test/java/org/trebol/security/services/impl/UserPermissionsServiceImplTest.java
Add unit and/or integration tests (where needed) and provide code coverage for the remaining components of the `org.trebol.security` package.
=> Test security components

src/test/java/org/trebol/payment/impl/webpayplus/WebpayplusPaymentServiceImplTest.java
Add unit tests for payment integration use cases using webpay plus.
=> test: cover `WebpayplusPaymentServiceImpl`

CHANGELOG.md, pom.xml
Mark this point as a new version. Update the changelog describing the latest PR's, including #238 #237 #236 #235 #233 and #231
=> Release 0.1.1

README.md
=> update and rephrase several parts of the README

CHANGELOG.md, README.md, pom.xml
=> Release v0.2.0

README.md
Add Java compatibility matrix 👍 
Closes: #258
=> Add Java compatibility matrix
